## A1

## Data Wrangling, I

Perform the following operations using Python on any open source dataset (e.g., data.csv)
1. Import all the required Python Libraries.
2. Locate an open source data from the web (e.g. https://www.kaggle.com). Provide a clear description of the data and its source (i.e., URL of the web site).
3. Load the Dataset into pandas data frame.
4. Data Preprocessing: check for missing values in the data using pandas insnull(), describe() function to get some initial statistics. Provide variable descriptions. Types of variables etc. Check the dimensions of the data frame.
5. Data Formatting and Data Normalization: Summarize the types of variables by checking the data types (i.e., character, numeric, integer, factor, and logical) of the variables in the data set. If variables are not in the correct data type, apply proper type conversions.
6. Turn categorical variables into quantitative variables in Python.

In addition to the codes and outputs, explain every operation that you do in the above steps and explain everything that you do to import/read/scrape the data set.


**1. Import Required Python Libraries**

In [ ]:
# numerical operations
import numpy as np
# Data handling and analysis
import pandas as pd
# Categorical to Quantitative variables encoding
from sklearn.preprocessing import LabelEncoder

**2. Link of Dataset(Melbourne Housing):**

https://www.kaggle.com/datasets/dansbecker/melbourne-housing-snapshot

**Description:**

This dataset contains information about house prices in Melbourne, Australia.
It includes details such as:
- price of the house
- number of rooms
- suburb
- land size
- distance from city center
- type of house
- seller information
- etc.

The dataset is commonly used for data preprocessing, data wrangling, and regression analysis.

**3. Load the Dataset into Pandas DataFrame**

In [ ]:
# Load the Melbourne Housing Dataset
df = pd.read_csv("melb_data.csv")

In [ ]:
# Display first 5 rows
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

**4. Data Preprocessing**

**4.1 Check Missing Values**

In [ ]:
# isnull() checks for missing values
# sum() counts missing values column-wise
# Column-wise no. of null values (sum)
df.isnull().sum()

Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Date                0
Distance            0
Postcode            0
Bedroom2            0
Bathroom            0
Car                62
Landsize            0
BuildingArea     6450
YearBuilt        5375
CouncilArea      1369
Lattitude           0
Longtitude          0
Regionname          0
Propertycount       0
dtype: int64

In [ ]:
# Displays null value(true/false) for first and last five rows all columns
df.isnull()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,True,False,False,False,False
13576,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
13577,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,True,False,False,False,False
13578,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
13579,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False

In [ ]:
# Check specific column for missing values
df['BuildingArea'].isnull()

0         True
1        False
2        False
3         True
4        False
         ...
13575     True
13576    False
13577     True
13578    False
13579    False
Name: BuildingArea, Length: 13580, dtype: bool

In [ ]:
# Check specific column for total no. of missing values
df['BuildingArea'].isnull().sum()

np.int64(6450)

In [ ]:
# Displays true/false for all columns whether a missing value exists
df.isnull().any()

Suburb           False
Address          False
Rooms            False
Type             False
Price            False
Method           False
SellerG          False
Date             False
Distance         False
Postcode         False
Bedroom2         False
Bathroom         False
Car               True
Landsize         False
BuildingArea      True
YearBuilt         True
CouncilArea       True
Lattitude        False
Longtitude       False
Regionname       False
Propertycount    False
dtype: bool

**Replace Missing Values with Mean, Median, Mode**

In [ ]:
df = pd.read_csv("melb_data.csv")
# Replaces missing values with the average value of the column.
df['BuildingArea'].fillna(df['BuildingArea'].mean())

0        151.96765
1         79.00000
2        150.00000
3        151.96765
4        142.00000
           ...
13575    151.96765
13576    133.00000
13577    151.96765
13578    157.00000
13579    112.00000
Name: BuildingArea, Length: 13580, dtype: float64

In [ ]:
df = pd.read_csv("melb_data.csv")
# Replaces missing values with median of the column.
df['BuildingArea'].fillna(df['BuildingArea'].median())

0        126.0
1         79.0
2        150.0
3        126.0
4        142.0
         ...
13575    126.0
13576    133.0
13577    126.0
13578    157.0
13579    112.0
Name: BuildingArea, Length: 13580, dtype: float64

In [ ]:
df = pd.read_csv("melb_data.csv")
# Replaces missing values with mode of the column.
df['BuildingArea'].fillna(df['BuildingArea'].mode())

0        120.0
1         79.0
2        150.0
3          NaN
4        142.0
         ...
13575      NaN
13576    133.0
13577      NaN
13578    157.0
13579    112.0
Name: BuildingArea, Length: 13580, dtype: float64

In [ ]:
df = pd.read_csv("melb_data.csv")
# Replaces missing values with a constant value e.g. 0
df['BuildingArea'].fillna(0)

0          0.0
1         79.0
2        150.0
3          0.0
4        142.0
         ...
13575      0.0
13576    133.0
13577      0.0
13578    157.0
13579    112.0
Name: BuildingArea, Length: 13580, dtype: float64

**4.2 Statistical Summary**
Describe dataset
Gives statistics like:
- count
- mean
- min
- max
- standard deviation

**Percentile/ Quartile: (25%, 50%, 75%)**
A percentile tells us how the data is distributed.
It shows the value below which a certain percentage of data falls.

Only applies to numerical columns

In [ ]:
df.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,13580.000000,1.358000e+04,13580.000000,13580.000000,13580.000000,13580.000000,13518.000000,13580.000000,7130.000000,8205.000000,13580.000000,13580.000000,13580.000000
mean,2.937997,1.075684e+06,10.137776,3105.301915,2.914728,1.534242,1.610075,558.416127,151.967650,1964.684217,-37.809203,144.995216,7454.417378
std,0.955748,6.393107e+05,5.868725,90.676964,0.965921,0.691712,0.962634,3990.669241,541.014538,37.273762,0.079260,0.103916,4378.581772
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,2.000000,6.500000e+05,6.100000,3044.000000,2.000000,1.000000,1.000000,177.000000,93.000000,1940.000000,-37.856822,144.929600,4380.000000
50%,3.000000,9.030000e+05,9.200000,3084.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.802355,145.000100,6555.000000
75%,3.000000,1.330000e+06,13.000000,3148.000000,3.000000,2.000000,2.000000,651.000000,174.000000,1999.000000,-37.756400,145.058305,10331.000000
max,10.000000,9.000000e+06,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

**4.3 Dataset Columns Description**

- **Suburb**: Name of the suburb where the property is located (Categorical / String)
- **Address**: Street address of the property (Categorical / String)
- **Rooms**: Total number of rooms in the property (Numerical – Integer)
- **Type**: Type of property  
  - h = house  
  - u = unit/apartment  
  - t = townhouse  
  (Categorical / String)
- **Price**: Price of the property in Australian dollars (Numerical – Float)
- **Method**: Method of sale (e.g., S = sold, SP = sold prior, PI = passed in) (Categorical / String)
- **SellerG**: Name of the real estate agent or seller (Categorical / String)
- **Date**: Date on which the property was sold (Categorical / String, can be converted to DateTime)
- **Distance**: Distance of the property from Melbourne CBD in kilometers (Numerical – Float)
- **Postcode**: Postal code of the property location (Numerical – Float)
- **Bedroom2**: Number of bedrooms in the property (Numerical – Float)
- **Bathroom**: Number of bathrooms in the property (Numerical – Float)
- **Car**: Number of car parking spaces available (Numerical – Float, contains missing values)
- **Landsize**: Total land size of the property in square meters (Numerical – Float)
- **BuildingArea**: Total building area in square meters (Numerical – Float, contains missing values)
- **YearBuilt**: Year in which the property was built (Numerical – Float, contains missing values)
- **CouncilArea**: Governing council area of the property (Categorical / String, contains missing values)
- **Lattitude**: Latitude coordinate of the property location (Numerical – Float)
- **Longtitude**: Longitude coordinate of the property location (Numerical – Float)
- **Regionname**: Region of Melbourne where the property is located (Categorical / String)
- **Propertycount**: Number of properties present in the suburb (Numerical – Float)

**4.4 Dataset Information**

In [ ]:
# Shows: column names, data types, non-null values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  object
 1   Address        13580 non-null  object
 2   Rooms          13580 non-null  int64
 3   Type           13580 non-null  object
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  object
 6   SellerG        13580 non-null  object
 7   Date           13580 non-null  object
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  float64
 10  Bedroom2       13580 non-null  float64
 11  Bathroom       13580 non-null  float64
 12  Car            13518 non-null  float64
 13  Landsize       13580 non-null  float64
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12211 non-null  object
 17  Lattitude      13580 non-null  float64
 18  Longtitude     13580 non-null  float64
 19  Regionname     13580 non-null  object
 20  Propertycount  13580 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 2.2+ MB

**4.5 Check Dimensions of Dataset**

In [ ]:
df.shape

(13580, 21)

**5. Data Formatting & Normalization**

**5.1 Check Data Types**

In [ ]:
df.dtypes

Suburb            object
Address           object
Rooms              int64
Type              object
Price            float64
Method            object
SellerG           object
Date              object
Distance         float64
Postcode         float64
Bedroom2         float64
Bathroom         float64
Car              float64
Landsize         float64
BuildingArea     float64
YearBuilt        float64
CouncilArea       object
Lattitude        float64
Longtitude       float64
Regionname        object
Propertycount    float64
dtype: object

**5.2 Type Conversion**

In [ ]:
# Convert object Type to string
df['Suburb'] = df['Suburb'].astype('string')

In [ ]:
df['Suburb'].dtype

string[python]

In [ ]:
# Convert Multiple Specific Columns
cols = ['Suburb', 'Address', 'SellerG']
df[cols] = df[cols].astype('string')

In [ ]:
# Convert object to categorical type
df['Type'] = df['Type'].astype('category')

In [ ]:
df['Type'].dtype

CategoricalDtype(categories=['h', 't', 'u'], ordered=False, categories_dtype=object)

In [ ]:
# Convert object to datetime type
df['Date'] = df['Date'].astype('datetime64[ns]')
# OR
# df['Date'] = pd.to_datetime(df['Date'])

In [ ]:
df['Date'].dtype

dtype('<M8[ns]')

In [ ]:
# Convert float64 to int64 type
df['Postcode'] = df['Postcode'].astype(int)

In [ ]:
df['Postcode'].dtype

dtype('int64')

In [ ]:
# Convert Multiple Columns Using Dictionary
df = df.astype({
    'Suburb': 'string',
    'Rooms': 'int',
    'Price': 'float',
    'Type': 'category',
    'Date': 'datetime64[ns]'
})

**6. Convert Categorical Variables into Numerical(Quantitative) Variables**

**6.1 Label Encoding**

Label Encoding converts each category into a unique number.

Converts categories into numbers

Example: h → 0, u → 1, t → 2

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Type_LabelEncoded'] = le.fit_transform(df['Type'])

df[['Type', 'Type_LabelEncoded']].head()

  Type  Type_LabelEncoded
0    h                  0
1    h                  0
2    h                  0
3    h                  0
4    h                  0

**6.2 One Hot Encoding**

One Hot Encoding creates separate binary columns for each category.

Creates separate binary columns

Avoids assigning order/priority to categories

In [ ]:
df = pd.read_csv('melb_data.csv')

onehot = pd.get_dummies(df['Type'], prefix='Type')
# OR Another column
# onehot = pd.get_dummies(df['Method'], prefix='Method')

df = pd.concat([df, onehot], axis=1)

df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Type_h,Type_t,Type_u
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0,True,False,False
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0,True,False,False
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0,True,False,False
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0,True,False,False
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0,True,False,False

**6.3 Dummy Coding**

Dummy coding is similar to One Hot Encoding but drops one category.

Dummy coding avoids dummy variable trap

Drops first category

If a categorical column has N categories, dummy encoding creates N − 1 columns.

In [ ]:
df = pd.read_csv('melb_data.csv')

dummy = pd.get_dummies(df['Type'], drop_first=True)
# OR Another column
# dummy = pd.get_dummies(df['Regionname'], drop_first=True)

df = pd.concat([df, dummy], axis=1)

df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,t,u
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0,False,False
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0,False,False
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0,False,False
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0,False,False
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0,False,False